theme: minima
header_pages:
  - index.md
  - setup.md
  - about_us.md
  - routes/administrator_route.md
  - routes/schools_route.md
  - routes/internet_providers_route.md
  - routes/login_route.md

title: Giga Token
minima:
  title: Giga Token
  skin: dark
  social_links:
    - { platform: site,  user_url: "https://investtools.com.br/en" }
    - { platform: devto, user_url: "https://br.linkedin.com/company/investtools" }
