name: CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    environment: Test

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Create .env file
        run: |
          touch .env
          echo "GIGA_AUTH_TOKEN=${{ secrets.GIGA_AUTH_TOKEN }}" >> .env
          echo "GIGA_URL=${{ secrets.GIGA_URL }}" >> .env
          echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" >> .env
          echo "NEXTAUTH_URL=${{ secrets.NEXTAUTH_URL }}" >> .env
          echo "NEXTAUTH_SECRET=${{ secrets.NEXTAUTH_SECRET }}" >> .env
          echo "GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }}" >> .env
          echo "GOOGLE_CLIENT_SECRET=${{ secrets.GOOGLE_CLIENT_SECRET }}" >> .env
          echo "ADMIN_EMAIL=${{ secrets.ADMIN_EMAIL }}" >> .env
          echo "ADMIN_ACCESS=${{ secrets.ADMIN_ACCESS }}" >> .env
          echo "NEXT_PUBLIC_GEOLOCATION_API_KEY=${{ secrets.NEXT_PUBLIC_GEOLOCATION_API_KEY }}" >> .env
          echo "NEXT_PUBLIC_REGISTER_ISP_URL=${{ secrets.NEXT_PUBLIC_REGISTER_ISP_URL }}" >> .env
          echo "NEXT_PUBLIC_REGISTER_ADMIN_URL=${{ secrets.NEXT_PUBLIC_REGISTER_ADMIN_URL }}" >> .env
          echo "NEXT_PUBLIC_SLACK_SIGNING_SECRET=${{ secrets.NEXT_PUBLIC_SLACK_SIGNING_SECRET }}" >> .env
          echo "NEXT_PUBLIC_SLACK_BOT_TOKEN=${{ secrets.NEXT_PUBLIC_SLACK_BOT_TOKEN }}" >> .env
          echo "NEXT_PUBLIC_SLACK_CHANNEL=${{ secrets.NEXT_PUBLIC_SLACK_CHANNEL }}" >> .env
          echo "NEXT_PUBLIC_CAPTCHA_KEY=${{ secrets.NEXT_PUBLIC_CAPTCHA_KEY }}" >> .env

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: latest

      - name: Install dependencies
        run: npm ci -f

      - name: Start local database
        run: npm run database:local:prepare

      - name: Run tests
        run: npm run test

      - name: Build
        run: npm run build
